name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(VersionMajor).$(VersionMinor).$(VersionPatch).$(Build.BuildId)$(PrereleaseLabel)

variables:
  - name: _version
    value: $(VersionMajor).$(VersionMinor).$(VersionPatch).$(Build.BuildId)
  - name: _packageVersion
    value: $(_version)$(PrereleaseLabel)
  - name: _publishNugetPackages
    value: $[or(eq(variables['PrereleaseLabel'], ''), eq(variables['PrereleaseLabel'], '-beta'))]

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $(Build.BuildNumber)
- script: echo $(_publishNugetPackages)

- script: dotnet build ./DataProcessor /warnaserror --configuration Release -p:Version=$(_version) -p:PackageVersion=$(_packageVersion) -p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
  displayName: Build solution      
